lexers: add mail lexer
martanne/vis pull request #904
Opened 2020-12-08 14:43 UTC by silasdb

2020-12-08 17:28 UTC, martanne requested changes
Could you please enforce that header field names need to start with a capital letter? Otherwise URLs at the start of lines are also highlighted.

Would it make sense to recognize inline PGP blocks? MIME sections? Mail signatures?

In general I wouldn't spend much time on it, but a more strict header field name rule seems useful.

2020-12-08 17:55 UTC, silasdb commented
On Tue, Dec 08, 2020 at 09:29:16AM -0800, Marc André Tanner wrote:
>Could you please enforce that header field names need to start with a capital letter? Otherwise URLs at the start of lines are also highlighted.

Sure, I will do that.

>Would it make sense to recognize inline PGP blocks? MIME sections? Mail signatures?
>
>In general I wouldn't spend much time on it, but a more strict header field name rule seems useful.

Perfect.  I'll work on that.  Besides improving header field parsing, and adding PGP blocks, MIME sections and mail signatures, what else am I missing?

2020-12-28 14:47 UTC, martanne requested changes
Please consider migrating the lexer to the new format, see #908 and #916.

Thanks

2020-12-28 14:47 UTC, martanne commented on lua/plugins/filetype.lua
> +		detect = function(file, data)
Please use `detect = function(_, data)` here, otherwise luacheck reports a warning because of the unused function argument, see #918.

2022-11-29 22:10 UTC, ninewise commented
Could you send the changes to the lexers upstream instead, to https://github.com/orbitalquark/scintillua? We're going to avoid diverging. The filetype changes are welcome, though, when you've send the actual lexer upstream.

2022-11-29 22:10 UTC, closed without merging